services:
  # --- BASE DE DONNÉES POSTGRESQL ---
  db:
    image: postgres:16-alpine
    container_name: lorcana-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    # Port retiré par sécurité, le réseau interne suffit !
    volumes:
      - lorcana-db-data:/var/lib/postgresql/data
    networks:
      - lorcana-internal

  # --- LORCANA TEAM TRACKER ---
  team-tracker:
    build: .
    container_name: loretracker
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tracker.rule=Host(`loretracker.fr`) || Host(`www.loretracker.fr`)"
      - "traefik.http.routers.tracker.entrypoints=websecure"
      - "traefik.http.routers.tracker.tls.certresolver=myresolver"
      - "traefik.http.services.tracker.loadbalancer.server.port=3000"
      - "traefik.docker.network=portfolio_app-network"
    networks:
      - lorcana-internal
      - app-network
    restart: always
    env_file:
      - .env

volumes:
  lorcana-db-data:

networks:
  lorcana-internal:
    driver: bridge
  app-network:
    external: true